### PR TITLE
Fix static analyzer complaints

### PR DESCRIPTION
**Pull request by mikaelhg**
Before I start with the bug fixing, I'm going to make various changes the static analyzer recommended, such as sun-style, move the unit tests to the JUnit 4 style, break down various large decision trees, and that kind of stuff.

### CODE REVIEW

**Comment by mikaelhg** [comment]
BTW, I just love the concept - I was writing a bunch of imperative scraping code, and this is so much better.

**Comment by mikaelhg** [comment]
Unfortunately it looks like that I won't be able to use webGrude for the purpose I was hoping, because of the static properties. I'll have to work on something similar, but probably Spring-integrated.

**Comment by beothorn** [comment]
Hey, I've been busy lately so sorry for taking so long to answer.
I like what you did with wiremock, pretty cool.
It's a shame webgrude will not work for you.
Thanks for the pull request!

**Comment by mikaelhg** [comment]
Thanks for building webGrude, it's a very neat concept!

**Pull request merged**
